#!/bin/sh

case $BLOCK_BUTTON in
    1) dmenu_run -fn Monospace-8 ;;
    3) notify-send --urgency=low -i /home/ben/Pictures/arch_transparent.png "I use Arch, btw..." ;;
esac

color="#00f0f0"

printf "<span color='%s'>\uf323</span>\n" "$color"
