#!/bin/sh

case $BLOCK_BUTTON in
    1) dmenu_run -fn Monospace-8 ;;
    3) notify-send -i /home/ben/Pictures/arch_transparent.png "I use Arch, btw..." ;;
esac

color="#008080"
logo=''

printf "<span color='%s'>       </span>\n" "$color"
