#!/bin/sh

case $BLOCK_BUTTON in
	1) $TERMINAL -e nmtui ;;
	3) notify-send "Internet" " ESSID: $(iwconfig wlp2s0 2> /dev/null | awk -F\" '{ print $2 }')
signal: $(grep "^\s*w" /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
" ;;
esac

wifi_status=$(cat /sys/class/net/w*/operstate)
signal_strength=$(grep "^\s*w" /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
essid=$(iwconfig wlp2s0 2> /dev/null | awk -F\" '{print $2}')

if [ "$wifi_status" == "down" ]; then
    wifi_icon="  "
elif [ "$wifi_status" == "up" ]; then
    wifi_icon=" "
else
    wifi_icon=" "
fi

if [ "$signal_strength" -gt "90" ]; then
    icon_color="#00f0f0"
elif (( 70 <= "$signal_strength" <= 90 )); then
    icon_color="#008080"
elif (( 30 <= "$signal_strength" < 70 )); then
    icon_color="#dcc30b"
else
    icon_color="#cc241d"
fi

printf " <span color='%s'><b>%s</b></span>\n" "$icon_color" "$wifi_icon"

