#!/bin/sh

# i3blocks module for pacman upgrades.
# Displays number of upgradeable packages.
# For this to work, have a `pacman -Sy` command run in the background as a
# cronjob every so often as root. This script will then read those packages.
# When clicked, it will run an upgrade via pacman.

case $BLOCK_BUTTON in
	1) $TERMINAL -e popupgrade ;;
    2) notify-send "Upgradable packages" "$(echo -e "" && /usr/bin/pacman -Qu | awk '{ print "<b>" $1 "</b>\n" $2 " -> " "<b><i>" $4 "</i></b>" "\n" }')" ;;
	3) pgrep -x dunst >/dev/null && notify-send "Upgrade module" "\- Left click to upgrade packages
- Middle click to show upgradable packages" ;;
esac

packages_count=$(pacman -Qu | grep -v "\[ignored\]" | wc -l | sed -e "s/^0$//g")

printf "<span><b>  $packages_count</b></span>\n"
