#!/bin/sh

# Checks to see if NordVPN has an active VPN connection

ifinstalled "nordvpn" || exit
status=$(nordvpn status | awk '/^Status/ {print $2}')

case $BLOCK_BUTTON in
    1) nordvpn c > /dev/null && notify-send "VPN" "Attempting to connect to the default VPN..." ;;
    2) nordvpn d > /dev/null && notify-send "VPN" "Disconnecting" ;;
    3) notify-send "VPN Status" "$status\n$(ipparser)" ;;
esac

if [ "$status" == "Connected" ]; then
    color="#00f0f0"
    symbol=" "
elif [ "$status" == "Connecting" ]; then
    color="#dcc30b"
    symbol=" "
else
    color="#cc241d"
    symbol=" "
fi

printf "<span color='%s'><b> %s%s</b></span>\n" "$color" "$symbol"
